/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cb50fbbe-df7b-4ce1-b0e6-c98cb5274ba8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_O8dTM3ra0",
    "aws_user_pools_web_client_id": "4dtpatk4am5ane8husi431etjr",
    "oauth": {}
};


export default awsmobile;
